spring:
  application:
    name: ${SPRING_APPLICATION_NAME:GlobusProject}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:docker,real-scheduler}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/globus_db}
    username: ${SPRING_DATASOURCE_USERNAME:globus_user}
    password: ${SPRING_DATASOURCE_PASSWORD:globus_pass}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: ${SPRING_LIQUIBASE_ENABLED:true}

bank:
  api:
    url: ${BANK_API_URL:https://cbr.ru/scripts/XML_daily.asp}

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    org.springframework.web: ${LOG_LEVEL_WEB:INFO}
    org.springframework.data: ${LOG_LEVEL_DATA:INFO}
    org.springdoc: ${LOG_LEVEL_SPRINGDOC:INFO}
    liquibase: ${LOG_LEVEL_LIQUIBASE:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
